recipe_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path("accounts/", include("allauth.urls")),
]

recipes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path("<slug:slug>/", views.RecipeDetail.as_view(), name="recipe_detail"),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# The core of the project, information about recipes are saved here.
class Recipe(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipes")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)


    class Meta():
        ordering = ["-created_on"]
    
    def __str__(self):
        return f"{self.title} | written by {self.author}"

# Going with ingredients as a separate model to allow any number of ingredients to be added to a recipe.
class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ingredients")
    content = models.CharField(max_length=100)

    def __str__(self):
        return f"ingredient: {self.pk} ({self.recipe.title})"

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Recipe

# Create your views here.

class RecipeList(generic.ListView):
    """
    Recipe list is the starting page of the website and shows a list of all recipes in the database.
    """
    model = Recipe
    template_name = "recipes/index.html"
    queryset = Recipe.objects.all()
    paginate_by = 4


class RecipeDetail(generic.DetailView):
    """
    Recipe detail view shows the author, creation date, text and ingredients of a recipe.
    """
    model = Recipe

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

recipes/templates/base.html
{% load static %}
{% url 'home' as home_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">    
</body>
</html>
<head>
    <title>Recipe Bank</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

    <!-- Navigation -->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="nav-item">
            <ul>
                <li>
                    <a class="{% if request.path == home_url %}active{% endif %}" href="{% url 'home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li>
	                <a class="{% if request.path == logout_url %}active{% endif %}" aria-current="page" href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a class="{% if request.path == signup_url %}active{% endif %}" aria-current="page"
                        href="{% url 'account_signup' %}">Register</a>
                </li>
                <li>
                    <a class="{% if request.path == login_url %}active{% endif %}" aria-current="page" href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="nav-item">
            {% if user.is_authenticated %}
            <p class="logged-in-text">user: {{ user }}</p>
            {% else %}
            <!--Nothing here for now-->
            <p></p>
            {% endif %}
        </div>
    </nav>

    <main class="ms-5">

        {% block content %}
        <!-- Content Goes here -->
        
        {% endblock content %}

    </main>

    <!-- Footer -->
    <footer>
        <nav class="navbar">
        <p>
            <a class="footer_link" href="https://github.com/KRnils">Made by KRN</a>
        </p>
        </nav>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

recipes/templates/recipes/index.html
{% extends "base.html" %}

{% block content %}
<!-- index.html content starts here -->
<div>
    <h1>Recipe entries</h1>
    <ul>
        {% for recipe in recipe_list %}
            <li>
                <a href="{% url 'recipe_detail' recipe.slug %}">
                    {{ recipe.title }} - {{ recipe.author }}
                </a>
            </li>
            <hr>
            {% if forloop.counter|divisibleby:2 %}
            {% endif %}
        {% endfor %}
    </ul>
</div>
    </div>
    {% if is_paginated %}
    <div aria-label="Page navigation">
        <ul>
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}"> &laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </div>
    {% endif %}
</div>
    
</body>
</html>
{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div>
    <div>
        <!-- Post title goes in these h1 tags -->
        <h1 >{{ recipe.title }}</h1>
        <!-- Post author goes before the | the post's created date goes after -->
        <p >{{ recipe.author }} | {{ recipe.created_on }}</p>
    </div>
</div>

<div>
    <div>
        <p>
            {{ recipe.text | safe }}
        </p>
    </div>
    <div>
        <ul>
            {% for item in recipe.ingredients.all %}
            <li>
                {{ item.content }}
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
{% url 'home' as home_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">    
</body>
</html>
<head>
    <title>Recipe Bank</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Font Awesome CSS -->

    <!-- Bootstrap CSS -->
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <p>You found the real base.html</p>
    <!-- Navigation -->
    <nav>
        <div>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
            </ul>
        </div>
    </nav>

    <main>

        {% block content %}
        <!-- Content Goes here -->
        
        {% endblock content %}

    </main>

    <!-- Footer -->
    <footer>
        <p>
            Footer goes here
        </p>
    </footer>
</body>
</html>